# Generated by Django 4.2.5 on 2023-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_productmodel_productitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'product/item', 'verbose_name_plural': 'Products/items'},
        ),
        migrations.AddField(
            model_name='productitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
