# Generated by Django 4.2.5 on 2023-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_productitem_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
