# Generated by Django 4.2.5 on 2023-10-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_productitem_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='is_avaliable',
            new_name='is_available',
        ),
    ]
